# install_apache.yml
---

- hosts: deb
# become root
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 pkg
    apt: 
      name: apache2

  - name: add php support for apache
    apt:
      name: libapache2-mod-php

